config/routes.rb
# encoding: utf-8
TorSearch::Application.routes.draw do

  get "trending/index"

  get "trending/search"

  devise_for :admin

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get 'a/r' => 'search#ad_redirect', as: :ad_redirect

  get 'errors/error_404'
  get 'errors/error_500'

  get 'graphs' => 'graphs#index', as: :graphs
  get 'graphs/daily' => 'graphs#daily', as: :daily
  get 'graphs/unique' => 'graphs#unique', as: :unique

  get 'r' => 'search#redirect', as: :redirect
  get 'flag' => 'domain#flag_page', as: :content_flag
  post 'flag' => 'domain#create_flag', as: :flags
  scope '(:locale)', locale: /en/ do
    devise_for :advertisers
    get '/search' => 'search#search', as: :search
    get 'add-domain' => 'domain#new', as: :add_link
    post 'add-domain' => 'domain#submit', as: :post_new_link

    get 'instant' => 'instant#new', as: :instant

    get 'advertising' => 'ads#advertising'
    post '/advertising' => 'contact#new_message'

    get '/contact' => 'contact#contact', as: :contact
    post '/contact' => 'contact#new_message', as: :messages
    get 'policies' => 'static#policies', as: :policies
    get '/humans.txt' => 'static#humans'
    get '/keyword_tool' => 'keyword_tool#index'

    get '/trending' => 'trending#index'
    get '/trending/explore' => 'trending#search'
  end
  get '/trending/graph' => 'trending#search_graph', as: :search_graph
  scope 'ads' do
    resources :campaigns, controller: :ad_campaigns do
      resources :ad_groups
      resources :ads
      resources :keywords, controller: :ad_group_keywords
    end
    resources :ad_groups do
      resources :ads
      resources :keywords, controller: :ad_group_keywords
    end
    resources :ads do
      get 'delete' => 'ads#delete', as: :delete
      get 'restore' => 'ads#restore', as: :restore
      get 'toggle' => 'ads#toggle', as: :toggle
      # put 'toggle' => 'ads#toggle', as: :toggle
    end
    resources :keywords, controller: :ad_group_keywords do
      post 'delete' => 'ad_group_keywords#delete', as: :delete
      get 'toggle' => 'ad_group_keywords#toggle', as: :toggle
      # put 'toggle' => 'ad_group_keywords#toggle', as: :toggle
    end
    resources :campaigns do
      get 'toggle' => 'ad_campaigns#toggle', as: :toggle
      # put 'toggle' => 'ad_campaigns#toggle', as: :toggle
    end
    resources :ad_groups do
      get 'toggle' => 'ad_groups#toggle', as: :toggle
      # put 'toggle' => 'ad_groups#toggle', as: :toggle
    end
    get 'billing' => 'billing#index', as: :billing
  end
  get '/ads' => 'ad_campaigns#index'

  post '/ads/bitcoin-address' => 'ads#get_payment_address', as: :new_address


  post 'payments' => 'payments#new_bitcoin_payment'

  post 'coupons' => 'coupon#create', as: :credit_coupon
  get '/ads/campaigns' => 'ad_campaigns#index', as: 'advertiser_root'
  root to: 'search#index'

  get '/:locale' => 'search#index', constraints: {locale: /en/}

  match '*not_found', to: 'errors#error_404', as: 'not_found', via: [:get, :post, :put] \
    unless Rails.application.config.consider_all_requests_local
end

app/models/ad_campaign.rb
class AdCampaign < ActiveRecord::Base
  acts_as_paranoid
  attr_accessible :name, :status, :paused, :advertiser, :advertiser_id, :default_bid
  belongs_to :advertiser
  has_many :ad_groups, dependent: :destroy
  has_many :ads, through: :ad_groups
end

app/controllers/ad_campaigns_controller.rb
# encoding: utf-8
class AdCampaignsController < AdsCommonController

  def index
    page = (params[:page] || 1).to_i
    per_page = (10).to_i
    @campaigns = @advertiser_campaigns \
      .page(page).per_page(per_page).order(:name, :created_at)
  end

  def show
    redirect_to campaign_ad_groups_path(params[:id]) and return
  end

  def new
    @campaign = AdCampaign.new(default_bid: 0.0001)
  end

  def create
    @campaign = AdCampaign.new(params[:ad_campaign])
    @campaign.advertiser = current_advertiser
    @campaign.name ||= "Default Campaign"
    if @campaign.save
      flash.notice << "Your campaign has been created successfully!"
      redirect_to new_ad_group_path({campaign_id: @campaign.id})
    else
      render 'new'
    end
  end

  def toggle
    model_name = current_advertiser.ad_campaigns.where(id: params[:id] || params[:campaign_id]).first
    if model_name.nil?
      flash.alert << 'There was a problem, try again soon!'
      redirect_to :back and return
    end
    model_name.paused = !model_name.paused
    if model_name.save
      @mixpanel_tracker.track(current_advertiser.id, 'toggled a Campaign', {keyword: {id: model_name.id}}, visitor_ip_address)
      flash.notice << 'Campaign Toggled'
    else
      flash.alert << 'There was a problem, try again soon!'
    end
    redirect_to :back
  end

end

app/views/ad_campaigns/_campaign_name.haml
%h4
  -if @ad_group
    %span.muted Ad Group:
    =@ad_group.name
  -else
    -if @campaign
      %span.muted Campaign:
      =@campaign.name
    -else
      All Online Campaigns

app/views/ad_campaigns/_nav_tabs.haml
%ul.nav.nav-tabs
  %li
  -if @campaign.nil?
    %li{class: (params[:controller] == 'ad_campaigns' && params[:action] == 'index') ? 'active' : '' }= link_to 'Campaigns', campaigns_path
  -if @ad_group.nil?
    -if @campaign.nil?
      %li{class: (params[:controller] == 'ad_groups' && params[:action] == 'index') ? 'active' : '' }= link_to 'Ad Groups', ad_groups_path
    -else
      %li{class: (params[:controller] == 'ad_groups' && params[:action] == 'index') ? 'active' : '' }= link_to 'Ad Groups', campaign_ad_groups_path(@campaign)
  %li{class: (params[:controller] == 'ads' && params[:action] == 'index') ? 'active' : '' }= link_to 'Ads', @campaign.nil? ? ads_path : campaign_ads_path(@campaign)
  -if @ad_group.present?
    %li{class: (params[:controller] == 'ad_group_keywords' && params[:action] == 'index') ? 'active' : ''}= link_to 'Keywords', ad_group_keywords_path
  -if @campaign.present?
    %li{class: (params[:controller] == 'ad_group_keywords' && params[:action] == 'index') ? 'active' : ''}= link_to 'Keywords', campaign_keywords_path(@campaign)
  -else
    %li{class: (params[:controller] == 'ad_group_keywords' && params[:action] == 'index') ? 'active' : ''}= link_to 'Keywords', keywords_path

app/views/ad_campaigns/index.haml
%h4 All Online Campaigns

=render partial: 'nav_tabs'
.row
  .span2
    %a.btn.btn-primary{href: new_campaign_path} + Campaign

.row
  %table.table.table-striped
    %thead
      %tr
        %th
        %th Status
        %th Campaign
        %th Campaign Start Date
    %tbody
      -@campaigns.each do |campaign|
        %tr
          %td
            -if campaign.paused?
              =link_to play_icon, campaign_toggle_path(campaign), class: 'btn btn-info'
            -else
              =link_to pause_icon, campaign_toggle_path(campaign), class: 'btn btn-default'
          %td= campaign.paused? ? "Paused" : "Active"
          %td= link_to campaign.name, campaign_ad_groups_path(campaign.try(:id))
          %td= campaign.created_at

app/views/ad_campaigns/new.haml
%h1 Create a new Campaign
=form_for @campaign, builder: WithErrorFields, url: {controller: "ad_campaigns"}, html: {novalidate: true } do |f|
  =f.label :name, "Campaign Name"
  =f.text_field :name
  =f.label :default_bid
  =f.number_field :default_bid
  %p.muted
    %small This bid applies to the first ad group in this campaign, which you'll create in the next step.
  =f.submit "Save and Continue", class: 'btn btn-success'

  %a.btn.btn-warning{href: campaigns_path} Cancel New Campaign

app/views/ad_campaigns/show.haml
=render partial: 'campaign_name'

=render partial: 'nav_tabs'