config/routes.rb
# encoding: utf-8
TorSearch::Application.routes.draw do

  get "trending/index"

  get "trending/search"

  devise_for :admin

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get 'a/r' => 'search#ad_redirect', as: :ad_redirect

  get 'errors/error_404'
  get 'errors/error_500'

  get 'graphs' => 'graphs#index', as: :graphs
  get 'graphs/daily' => 'graphs#daily', as: :daily
  get 'graphs/unique' => 'graphs#unique', as: :unique

  get 'r' => 'search#redirect', as: :redirect
  get 'flag' => 'domain#flag_page', as: :content_flag
  post 'flag' => 'domain#create_flag', as: :flags
  scope '(:locale)', locale: /en/ do
    devise_for :advertisers
    get '/search' => 'search#search', as: :search
    get 'add-domain' => 'domain#new', as: :add_link
    post 'add-domain' => 'domain#submit', as: :post_new_link

    get 'instant' => 'instant#new', as: :instant

    get 'advertising' => 'ads#advertising'
    post '/advertising' => 'contact#new_message'

    get '/contact' => 'contact#contact', as: :contact
    post '/contact' => 'contact#new_message', as: :messages
    get 'policies' => 'static#policies', as: :policies
    get '/humans.txt' => 'static#humans'
    get '/keyword_tool' => 'keyword_tool#index'

    get '/trending' => 'trending#index'
    get '/trending/explore' => 'trending#search'
  end
  get '/trending/graph' => 'trending#search_graph', as: :search_graph
  scope 'ads' do
    resources :campaigns, controller: :ad_campaigns do
      resources :ad_groups
      resources :ads
      resources :keywords, controller: :ad_group_keywords
    end
    resources :ad_groups do
      resources :ads
      resources :keywords, controller: :ad_group_keywords
    end
    resources :ads do
      get 'delete' => 'ads#delete', as: :delete
      get 'restore' => 'ads#restore', as: :restore
      get 'toggle' => 'ads#toggle', as: :toggle
      # put 'toggle' => 'ads#toggle', as: :toggle
    end
    resources :keywords, controller: :ad_group_keywords do
      post 'delete' => 'ad_group_keywords#delete', as: :delete
      get 'toggle' => 'ad_group_keywords#toggle', as: :toggle
      # put 'toggle' => 'ad_group_keywords#toggle', as: :toggle
    end
    resources :campaigns do
      get 'toggle' => 'ad_campaigns#toggle', as: :toggle
      # put 'toggle' => 'ad_campaigns#toggle', as: :toggle
    end
    resources :ad_groups do
      get 'toggle' => 'ad_groups#toggle', as: :toggle
      # put 'toggle' => 'ad_groups#toggle', as: :toggle
    end
    get 'billing' => 'billing#index', as: :billing
  end
  get '/ads' => 'ad_campaigns#index'

  post '/ads/bitcoin-address' => 'ads#get_payment_address', as: :new_address


  post 'payments' => 'payments#new_bitcoin_payment'

  post 'coupons' => 'coupon#create', as: :credit_coupon
  get '/ads/campaigns' => 'ad_campaigns#index', as: 'advertiser_root'
  root to: 'search#index'

  get '/:locale' => 'search#index', constraints: {locale: /en/}

  match '*not_found', to: 'errors#error_404', as: 'not_found', via: [:get, :post, :put] \
    unless Rails.application.config.consider_all_requests_local
end

app/controllers/billing_controller.rb
# encoding: utf-8
class BillingController < ApplicationController
  layout 'ads'
  before_filter :authenticate_advertiser!
  before_filter :set_campaigns_up

  def index
    if current_advertiser.bitcoin_addresses.empty?
      flash.now[:notice] << "We've generated a new bitcoin address for you!"
      BitcoinAddress.generate_new_address(current_advertiser)
    end
    @transactions = {}
    @transactions[:this_month] = current_advertiser.payments.where(created_at: DateTime.now.beginning_of_month..DateTime.now).order(:created_at).reverse_order
    @transactions[:last_month] = current_advertiser.payments.where(created_at: 1.month.ago.beginning_of_month..1.month.ago.end_of_month).order(:created_at).reverse_order
    @transactions[:months_ago] = current_advertiser.payments.where(created_at: 2.months.ago.beginning_of_month..2.months.ago.end_of_month).order(:created_at).reverse_order
  end

  private

  def set_campaigns_up
    @advertiser_campaigns = current_advertiser.ad_campaigns.order(:name)
    @advertiser_ad_groups = current_advertiser.ad_groups.order(:name).group_by(&:ad_campaign_id)
  end
end

app/views/billing/index.haml
%h4 Billing

.row
  .span4
    %h5 Current Balance
    =number_to_currency(current_advertiser.balance, precision: 8, unit: '&#x0e3f;'.html_safe, format: "%u%n")
    =form_for :coupon, class: 'form-inline', url: credit_coupon_path do |f|
      .input-append
        =f.text_field :code, {placeholder: t("ads.coupon_code"), class: 'input-medium', id: "appendedInputButtons"}
        %button.btn{type: "submit"}= t('ads.apply')
  .span4
    %h5 Newest Bitcoin Address
    -address = current_advertiser.bitcoin_addresses.order(:created_at).last
    =address
    =form_tag(new_address_path) do |f|
      %button.btn.btn-info{type: 'submit', disabled: (address.created_at > 1.hour.ago ) ? true : false} Request a new Bitcoin Address

  .row
    %table.table.table-striped
      %thead
        %tr
          %th Date
          %th Coupon Code
          %th Bitcoin Address
          %th Amount
          %th Notes
      %tbody
        %tr.info
          %td{colspan: 5}
            =DateTime.now.beginning_of_month.strftime('%b %e, %Y')
            ='-'
            =DateTime.now.strftime('%b %e, %Y')
        -if @transactions[:this_month].any?
          -@transactions[:this_month].each do |t|
            %tr
              %td= t.created_at.strftime('%b %e, %Y')
              %td= t.coupon.try(:code)
              %td= t.bitcoin_address.try(:address)
              %td= t.amount
              %td
                -if t.is_bonus?
                  Bonus
        -else
          %tr
            %td{colspan: 5} No transactions for this date range
        %tr.info
          %td{colspan: 5}
            =1.month.ago.beginning_of_month.strftime('%b %e, %Y')
            ='-'
            =1.month.ago.end_of_month.strftime('%b %e, %Y')
        -if @transactions[:last_month].any?
          -@transactions[:last_month].each do |t|
            %tr
              %td= t.created_at.strftime('%b %e, %Y')
              %td= t.coupon.try(:code)
              %td= t.bitcoin_address.try(:address)
              %td= t.amount
              %td
                -if t.is_bonus?
                  Bonus
        -else
          %tr
            %td{colspan: 5} No transactions for this date range
        %tr.info
          %td{colspan: 5}
            =2.months.ago.beginning_of_month.strftime('%b %e, %Y')
            ='-'
            =2.months.ago.end_of_month.strftime('%b %e, %Y')
        -if @transactions[:months_ago].any?
          -@transactions[:months_ago].each do |t|
            %tr
              %td= t.created_at.strftime('%b %e, %Y')
              %td= t.coupon.try(:code)
              %td= t.bitcoin_address.try(:address)
              %td= t.amount
              %td
                -if t.is_bonus?
                  Bonus
        -else
          %tr
            %td{colspan: 5} No transactions for this date range