config/routes.rb
# encoding: utf-8
TorSearch::Application.routes.draw do

  get "trending/index"

  get "trending/search"

  devise_for :admin

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get 'a/r' => 'search#ad_redirect', as: :ad_redirect

  get 'errors/error_404'
  get 'errors/error_500'

  get 'graphs' => 'graphs#index', as: :graphs
  get 'graphs/daily' => 'graphs#daily', as: :daily
  get 'graphs/unique' => 'graphs#unique', as: :unique

  get 'r' => 'search#redirect', as: :redirect
  get 'flag' => 'domain#flag_page', as: :content_flag
  post 'flag' => 'domain#create_flag', as: :flags
  scope '(:locale)', locale: /en/ do
    devise_for :advertisers
    get '/search' => 'search#search', as: :search
    get 'add-domain' => 'domain#new', as: :add_link
    post 'add-domain' => 'domain#submit', as: :post_new_link

    get 'instant' => 'instant#new', as: :instant

    get 'advertising' => 'ads#advertising'
    post '/advertising' => 'contact#new_message'

    get '/contact' => 'contact#contact', as: :contact
    post '/contact' => 'contact#new_message', as: :messages
    get 'policies' => 'static#policies', as: :policies
    get '/humans.txt' => 'static#humans'
    get '/keyword_tool' => 'keyword_tool#index'

    get '/trending' => 'trending#index'
    get '/trending/explore' => 'trending#search'
  end
  get '/trending/graph' => 'trending#search_graph', as: :search_graph
  scope 'ads' do
    resources :campaigns, controller: :ad_campaigns do
      resources :ad_groups
      resources :ads
      resources :keywords, controller: :ad_group_keywords
    end
    resources :ad_groups do
      resources :ads
      resources :keywords, controller: :ad_group_keywords
    end
    resources :ads do
      get 'delete' => 'ads#delete', as: :delete
      get 'restore' => 'ads#restore', as: :restore
      get 'toggle' => 'ads#toggle', as: :toggle
      # put 'toggle' => 'ads#toggle', as: :toggle
    end
    resources :keywords, controller: :ad_group_keywords do
      post 'delete' => 'ad_group_keywords#delete', as: :delete
      get 'toggle' => 'ad_group_keywords#toggle', as: :toggle
      # put 'toggle' => 'ad_group_keywords#toggle', as: :toggle
    end
    resources :campaigns do
      get 'toggle' => 'ad_campaigns#toggle', as: :toggle
      # put 'toggle' => 'ad_campaigns#toggle', as: :toggle
    end
    resources :ad_groups do
      get 'toggle' => 'ad_groups#toggle', as: :toggle
      # put 'toggle' => 'ad_groups#toggle', as: :toggle
    end
    get 'billing' => 'billing#index', as: :billing
  end
  get '/ads' => 'ad_campaigns#index'

  post '/ads/bitcoin-address' => 'ads#get_payment_address', as: :new_address


  post 'payments' => 'payments#new_bitcoin_payment'

  post 'coupons' => 'coupon#create', as: :credit_coupon
  get '/ads/campaigns' => 'ad_campaigns#index', as: 'advertiser_root'
  root to: 'search#index'

  get '/:locale' => 'search#index', constraints: {locale: /en/}

  match '*not_found', to: 'errors#error_404', as: 'not_found', via: [:get, :post, :put] \
    unless Rails.application.config.consider_all_requests_local
end

app/models/ad_group_keyword.rb
class AdGroupKeyword < ActiveRecord::Base
  belongs_to :ad_group
  belongs_to :keyword
  has_many :ads, through: :ad_group
  attr_accessible :ad_group_id, :ad_group, :keyword_id, :keyword, :bid, :paused
  validates :ad_group_id, uniqueness: { scope: [:keyword_id, :ad_group_id] }
  validates :keyword, presence: true
  scope :valid, -> {
    where('ad_group_keywords.bid <= advertisers.balance') \
    .joins(:ad_group) \
    .joins('LEFT JOIN advertisers ON advertisers.id = ad_groups.advertiser_id')
  }
  delegate :word, to: :keyword, allow_nil: true
  def status
    if paused?
      "Paused"
    else
      "Active"
    end
  end

  def ctr
    if views.present? && views > 0 && clicks.present? && clicks > 0
      clicks / views.to_f
    else
      0
    end * 100
  end

  def self.refresh_counts!
    AdGroupKeyword.connection.execute(
      <<-SQL
WITH click_counts AS (
  SELECT count(ad_clicks.keyword_id) as clicks_count, ad_clicks.keyword_id as keyword_id
  FROM ad_clicks
  LEFT JOIN ads
  ON ad_clicks.ad_id = ads.id
  WHERE ads.deleted_at IS NULL
  GROUP BY ad_clicks.keyword_id
), view_counts AS (
  SELECT count(ad_views.keyword_id) as views_count, ad_views.keyword_id as keyword_id
  FROM ad_views
  LEFT JOIN ads
  ON ad_views.ad_id = ads.id
  WHERE ads.deleted_at IS NULL
  GROUP BY ad_views.keyword_id
), keyword_stats AS (
  SELECT click_counts.clicks_count as clicks, view_counts.views_count AS views, view_counts.keyword_id
  FROM click_counts
  JOIN view_counts ON view_counts.keyword_id = click_counts.keyword_id
)
UPDATE ad_group_keywords
  SET clicks = COALESCE((SELECT clicks FROM keyword_stats WHERE keyword_stats.keyword_id = ad_group_keywords.keyword_id), 0),
  views = COALESCE((SELECT views FROM keyword_stats WHERE keyword_stats.keyword_id = ad_group_keywords.keyword_id), 0)
      SQL
    )
  end
end

app/controllers/ad_group_keywords_controller.rb
# encoding: utf-8
class AdGroupKeywordsController < AdsCommonController

  def index
    page = (params[:page] || 1).to_i
    per_page = 15
    if params[:ad_group_id]
      @ad_group = current_advertiser.ad_groups.where(id: params[:ad_group_id]).first
      @campaign = @ad_group.ad_campaign
    elsif params[:ad_group_id].nil? && params[:campaign_id]
      @campaign = current_advertiser.ad_campaigns.where(id: params[:campaign_id]).first
    end

    keywords = current_advertiser.ad_group_keywords

    keywords = keywords.where(ad_group_id: @ad_group.id) if @ad_group
    if @ad_group.nil? && @campaign
      ad_group_ids = @campaign.ad_groups.pluck(:id)
      keywords = keywords.where(ad_group_id: ad_group_ids)
    end

    @keywords = keywords.joins(:keyword).order('keywords.word asc').order( :created_at).page(page).per_page(per_page)
  end

  def edit
    @keyword = current_advertiser.ad_group_keywords.where(id: params[:id]).first
  end

  def update
    @keyword = current_advertiser.ad_group_keywords.where(id: params[:id]).first
    word = params[:ad_group_keyword][:keyword].strip
    key = Keyword.find_or_create_by_word(word)
    @keyword.keyword_id = key.id
    @keyword.bid = params[:ad_group_keyword][:bid]
    existing_keywords = current_advertiser \
        .ad_group_keywords \
        .where(keyword_id: key.id, ad_group_id: @keyword.ad_group_id) \
        .where( 'ad_group_keywords.id <> ?', @keyword.id)

    if existing_keywords.any?
      flash.alert << "You already have this keyword on this ad group"
      redirect_to :back and return
    end
    if @keyword.save
      @mixpanel_tracker.track(current_advertiser.id, 'toggled a keyword', {keyword: {id: @keyword.id, title: word}}, visitor_ip_address)
      flash.notice << 'Keyword Updated'
      redirect_to ad_group_keywords_path(@keyword.ad_group_id) and return
    else
      flash.alert << 'There was a problem, please try again!'
      render :edit
    end
  end

  def new
    @ad_group = current_advertiser.ad_groups.where(id: params[:ad_group_id]).first if params[:ad_group_id]
  end

  def create
    if  params[:ad_group_id].nil? && (params[:ad_group].nil? || params[:ad_group][:id].nil?)
      flash[:alert] << "You must select an ad group"
      redirect_to new_keyword_path and return
    end
    ad_group = current_advertiser.ad_groups.where(id: (params[:ad_group_id] || params[:ad_group][:id])).first
    if ad_group.nil?
      flash[:alert] << "There was a problem handling your request, please try again"
      redirect_to new_keyword_path and return
    end
    if (params[:keywords] && params[:keywords].is_a?(String))
      keywords = params[:keywords].split(/\n/)
      if keywords.count == 1
        keywords = params[:keywords].split(/,/)
      end
      @keywords = []
      keywords.map do |k|
        word = k.strip
        keyword = Keyword.find_or_create_by_word(word)
        @keywords << AdGroupKeyword.new(ad_group_id: ad_group.id, keyword_id: keyword.id, bid: ad_group.ad_campaign.default_bid || 0.0001)
      end
      render :new
    else
      params[:keyword].each do |k, bid|
        word = k.strip
        keyword = Keyword.find_or_create_by_word(word)
        AdGroupKeyword.create(ad_group_id: params[:ad_group_id], keyword_id: keyword.id, bid: bid)
      end
      redirect_to ad_group_keywords_path(ad_group) and return
    end
  end

  def delete
    keyword = current_advertiser.ad_group_keywords.where(id: params[:keyword_id]).first
    kw = keyword.keyword.word
    if keyword.destroy
      flash.notice << "Successfully removed #{kw}"
    else
      flash.alert << "Something went wrong, please try again later"
    end
    redirect_to :back
  end

  def toggle
    keyword = current_advertiser.ad_group_keywords.where(id: params[:id] || params[:keyword_id]).first
    if keyword.nil?
      flash.alert << 'There was a problem, try again soon!'
      redirect_to :back
    end
    keyword.paused = !keyword.paused
    if keyword.save
      @mixpanel_tracker.track(current_advertiser.id, 'toggled a keyword', {keyword: {id: keyword.id, title: keyword.keyword.word}}, visitor_ip_address)
      flash.notice << 'Keyword Toggled'
    else
      flash.alert << 'There was a problem, try again soon!'
    end
    redirect_to :back
  end
end

app/views/ad_group_keywords/edit.haml
=form_for @keyword, builder: WithErrorFields do |f|
  =f.label :word
  =f.text_field :keyword, value: @keyword.keyword.word
  =f.label :bid
  =f.text_field :bid
  =f.submit "Save", class: 'btn btn-success'
  %br/
  =link_to "Cancel", :back, class: 'btn btn-warning'

app/views/ad_group_keywords/index.haml
=render partial: 'ad_campaigns/campaign_name'
-if @ad_group
  =render partial: 'ad_groups/nav_tabs'
-else
  =render partial: 'ad_campaigns/nav_tabs'

%a.btn.btn-primary{href: (defined?(@ad_group)) ? new_keyword_path(ad_group_id: @ad_group.id) : new_keyword_path} + Keyword
.row
  %table.table.table-striped
    %thead
      %th
      %th Word
      %th Campaign
      %th Ad Group
      %th
        Searches Last
        %br/
        30 Days
      %th Status
      %th Clicks
      %th Impr.
      %th CTR
      %th Current Bid
    %tbody
      -@keywords.each do |keyword|
        %tr
          %td
            %ul.list-unstyled
              %li
                =link_to edit_icon, edit_keyword_path(keyword), class: 'btn btn-info'
              %li
                -if keyword.paused?
                  =link_to play_icon, keyword_toggle_path(keyword), class: 'btn btn-info'
                -else
                  =link_to pause_icon, keyword_toggle_path(keyword), class: 'btn btn-default'
              %li
                =form_for keyword, as: :keyword, url: keyword_delete_path(keyword), method: :post do |f|
                  =f.hidden_field :delete, value: true
                  =f.hidden_field :id
                  %button{type: 'submit', class: 'btn btn-warning'}
                    = delete_icon

          %td= keyword.keyword.word
          %td= link_to keyword.ad_group.ad_campaign.name, campaign_path(keyword.ad_group.ad_campaign)
          %td= link_to keyword.ad_group.name, keyword.ad_group
          %td
            -if keyword.keyword.searches_counts.nil?
              Pending
            -else
              -if keyword.keyword.status_id == 0
                =down_icon
              -elsif keyword.keyword.status_id == 1
                =still_icon
              -else
                =up_icon
              = keyword.keyword.searches_counts unless keyword.keyword.searches_counts == 0
          %td= keyword.status
          %td= keyword.clicks
          %td= keyword.views
          %td= number_to_percentage(keyword.ctr, precision: 2)
          %td= number_to_currency(keyword.bid, precision: 8, unit: "&#x0e3f;".html_safe, format: "%u%n")
.row
  =will_paginate(@keywords)

app/views/ad_group_keywords/new.haml
-if @keywords
  =form_tag '/ads/keywords', novalidate: true, class: 'form-horizontal' do
    =hidden_field_tag :ad_group_id, @keywords.first.ad_group_id
    %fieldset{disabled: true}
      .form-group
        =label_tag 'Keyword', 'Keyword', class: 'col-sm-3'
        =text_field_tag '', 'Bid', class: 'form-control col-sm-8'
    -@keywords.each do |keyword|
      -word = keyword.keyword.word
      .form-group
        =label_tag word, word, class: 'col-sm-3'
        =text_field_tag "keyword[#{word}]", keyword.bid, class: 'form-control col-sm-8'
    =submit_tag "Save", class: 'btn btn-success'
    %a.btn{href: campaigns_path} Cancel
-else
  =form_tag '/ads/keywords', novalidate: true do
    .row
      -if @ad_group.nil?
        =label_tag :ad_group, "Select an Ad Group"
        =collection_select(:ad_group, :id, current_advertiser.ad_groups, :id, :name, {prompt: true})
      -else
        =hidden_field_tag :ad_group_id, @ad_group.id
    .row
      %p Add keywords

      %p
        Choose phrases that customers would use to search for your products and services.

      Enter one keyword per line.
    .row
      .col-sm-8
        =text_area_tag :keywords,'', {rows: 3, class: 'form-control', placeholder: 'Add your keywords here'}
    =submit_tag "Save", class: 'btn btn-success'
    %a.btn.btn-warning{href: campaigns_path} Cancel