config/routes.rb
# encoding: utf-8
TorSearch::Application.routes.draw do

  get "trending/index"

  get "trending/search"

  devise_for :admin

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get 'a/r' => 'search#ad_redirect', as: :ad_redirect

  get 'errors/error_404'
  get 'errors/error_500'

  get 'graphs' => 'graphs#index', as: :graphs
  get 'graphs/daily' => 'graphs#daily', as: :daily
  get 'graphs/unique' => 'graphs#unique', as: :unique

  get 'r' => 'search#redirect', as: :redirect
  get 'flag' => 'domain#flag_page', as: :content_flag
  post 'flag' => 'domain#create_flag', as: :flags
  scope '(:locale)', locale: /en/ do
    devise_for :advertisers
    get '/search' => 'search#search', as: :search
    get 'add-domain' => 'domain#new', as: :add_link
    post 'add-domain' => 'domain#submit', as: :post_new_link

    get 'instant' => 'instant#new', as: :instant

    get 'advertising' => 'ads#advertising'
    post '/advertising' => 'contact#new_message'

    get '/contact' => 'contact#contact', as: :contact
    post '/contact' => 'contact#new_message', as: :messages
    get 'policies' => 'static#policies', as: :policies
    get '/humans.txt' => 'static#humans'
    get '/keyword_tool' => 'keyword_tool#index'

    get '/trending' => 'trending#index'
    get '/trending/explore' => 'trending#search'
  end
  get '/trending/graph' => 'trending#search_graph', as: :search_graph
  scope 'ads' do
    resources :campaigns, controller: :ad_campaigns do
      resources :ad_groups
      resources :ads
      resources :keywords, controller: :ad_group_keywords
    end
    resources :ad_groups do
      resources :ads
      resources :keywords, controller: :ad_group_keywords
    end
    resources :ads do
      get 'delete' => 'ads#delete', as: :delete
      get 'restore' => 'ads#restore', as: :restore
      get 'toggle' => 'ads#toggle', as: :toggle
      # put 'toggle' => 'ads#toggle', as: :toggle
    end
    resources :keywords, controller: :ad_group_keywords do
      post 'delete' => 'ad_group_keywords#delete', as: :delete
      get 'toggle' => 'ad_group_keywords#toggle', as: :toggle
      # put 'toggle' => 'ad_group_keywords#toggle', as: :toggle
    end
    resources :campaigns do
      get 'toggle' => 'ad_campaigns#toggle', as: :toggle
      # put 'toggle' => 'ad_campaigns#toggle', as: :toggle
    end
    resources :ad_groups do
      get 'toggle' => 'ad_groups#toggle', as: :toggle
      # put 'toggle' => 'ad_groups#toggle', as: :toggle
    end
    get 'billing' => 'billing#index', as: :billing
  end
  get '/ads' => 'ad_campaigns#index'

  post '/ads/bitcoin-address' => 'ads#get_payment_address', as: :new_address


  post 'payments' => 'payments#new_bitcoin_payment'

  post 'coupons' => 'coupon#create', as: :credit_coupon
  get '/ads/campaigns' => 'ad_campaigns#index', as: 'advertiser_root'
  root to: 'search#index'

  get '/:locale' => 'search#index', constraints: {locale: /en/}

  match '*not_found', to: 'errors#error_404', as: 'not_found', via: [:get, :post, :put] \
    unless Rails.application.config.consider_all_requests_local
end

app/controllers/trending_controller.rb
class TrendingController < ApplicationController
  def index
    @trending_searches = read_through_cache('trending_searches', 1.hour) do
      Query.trending
    end
    @max = 0
    @trending_searches.each { |s| @max = s[:volume].to_f if s[:volume].to_f > @max }
    @max *= 1.2
  end

  def search

  end

  def search_graph
    keywords = params[:q].map{|q|q.downcase.strip}.reject(&:empty?)[0..2]
    if current_advertiser
      @mixpanel_tracker.track(current_advertiser.id, 'Checked Trending', {keywords: keywords})
    else
      @mixpanel_tracker.track('Guest', 'Checked Trending', {keywords: keywords})
    end

    g = Gruff::Line.new('940x400')

    g.title = "Searches for #{keywords.join(', ')}"
    green = '#00ff00'
    grey = '#333333'
    orange = '#ff5d00'
    red = '#f61100'
    white = 'white'
    light_grey = '#999999'
    black = 'black'
    colors = [green, grey, orange, red, white, light_grey, black]
    g.theme = {
      colors: colors,
      marker_color: 'blue',
      background_colors: %w(white white)
    }
    start = DateTime.parse('September 1, 2013').to_date
    months = ((Date.today - start).to_f / 30).to_i + 1
    labels = []
    months.times do |i|
      labels << (start + i.months)
    end
    g.labels = {}
    g.hide_legend = false
    g.maximum_value = 1
    g.minimum_value = 0
    g.hide_dots = true

    keywords.each do |keyword|
      searches_data = []
      searches = read_through_cache("searches_for_#{keyword}", 1.week) do
        Search.joins(:query) \
          .where('lower(term) like ?', "%#{keyword}%") \
          .group("to_char(searches.created_at, 'YYYY-MM')") \
          .order("to_char(searches.created_at, 'YYYY-MM')").count
      end

      labels.each_with_index do |date, index|
        d = date.strftime('%Y-%m')
        g.labels[index] = date.strftime('%b %Y')
        searches_data << if searches[d]
          searches[d]
        else 0
        end
      end

      g.data(keyword.titleize, searches_data)
    end


    data = g.to_blob('PNG')
    #end
    send_data data, type: 'image/png', disposition: :inline
  end
end

app/helpers/trending_helper.rb
module TrendingHelper
end

app/views/trending/index.html.haml
-content_for :above_container do
  -render partial: 'layouts/ads_nav', locals: {title: 'Trending Searches', path: trending_path}
%h1 Trending
.row
  .col-md-5.col-md-offset-1
    .row
      %h2 Right Now
    .row
      -if @trending_searches.any?
        %dl
        -@trending_searches.each do |search|
          %dt= link_to search[:term], trending_search_path(q: [search[:term]])
          %dd
            .row
              .col-md-6
                .progress
                  -amount = ((search[:volume].to_f / @max.to_f) * 100)
                  .progress-bar.progress-bar-info{style: "width: #{amount}%"}
              .col-md-6
                %strong #{search[:volume]}+
                Searches
        %p.muted
          queries are selected based on the difference between the last 6 hours vs the same period yesterday
      -else
        %p Nothing found :(
  .col-md-6
    %p Compare up to 3 queries at a time
    =form_tag(trending_search_path, method: "get", id: 'search', class: 'form-inline') do
      .input-append.col-md-12
        =text_field_tag 'q[]', '', class: 'col-md-1 form-control', placeholder: '1st term'
        =text_field_tag 'q[]', '', class: 'col-md-1 form-control', placeholder: '2nd term'
        =text_field_tag 'q[]', '', class: 'col-md-1 form-control', placeholder: '3rd term', id: "appendedInputButtons"
        =button_tag glyphicon('search'), class: 'btn btn-default', type: "submit", name: ''

app/views/trending/search.html.haml
-content_for :above_container do
  -render partial: 'layouts/ads_nav', locals: {title: 'Search Trends', path: trending_path}
%h1 Trending
.row
  =form_tag(trending_search_path, method: "get", id: 'search', class: 'form-inline') do
    .input-append.col-md-10
      =text_field_tag 'q[]', params[:q][0], class: 'col-md-2 form-control', placeholder: '1st term'
      =text_field_tag 'q[]', params[:q][1], class: 'col-md-2 form-control', placeholder: '2nd term'
      =text_field_tag 'q[]', params[:q][2], class: 'col-md-2 form-control', placeholder: '3rd term', id: "appendedInputButtons"
      =button_tag glyphicon('search'), class: 'btn btn-default', type: "submit", name: ''
%hr/
.row
  .trending_graph
    <img src="#{ search_graph_path(q: params[:q]) }"/>